# This is the SAM template that represents the architecture of your serverless application
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-template-basics.html
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Description: >-
  whatcoin

Parameters:
  BotApiToken:
    Type: String
    Description: Telegram bot api token

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # Each Lambda function is defined by properties:
  # https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction

  # This is a Lambda function config associated with the source code: webhook.js
  WebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/webhook.webhook
      Runtime: nodejs14.x
      Description: Webhook to receive updates from the Telegram bot API
      MemorySize: 1536
      Timeout: 50
      Environment:
        Variables:
          BOT_API_TOKEN: !Ref BotApiToken
          NODE_ENV: production
          FONTCONFIG_PATH: ./fonts
      Events:
        Webhook:
          Type: HttpApi # More info about HttpApi Event Source: https://github.com/aws/serverless-application-model/blob/master/versions/2016-10-31.md#httpapi
          Properties:
            Path: /webhook
            Method: POST

Outputs:
  # ServerlessHttpApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  WebhookApi:
    Description: 'HTTP API endpoint URL for Telegram webhook'
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/webhook'
